server:
  port: 3001
spring:
  application:
    name: seata-storage-service
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.139.56.235:3306/seata_storage?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        namespace: bd4cc79e-b647-43c9-8f2b-6ea3f5b8e712
        server-addr: 127.0.0.1:8848

# mapper xml
mybatis:
  mapper-locations: classpath:mapper/*.xml

# openFeign
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

# seata
seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: scorpios_tx_group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      username: nacos
      password: nacos
      namespace: bd4cc79e-b647-43c9-8f2b-6ea3f5b8e712
      cluster: default
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: bd4cc79e-b647-43c9-8f2b-6ea3f5b8e712
      group: SEATA_GROUP
      username: nacos
      password: nacos
